USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/sony/E2303/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_NO_SEPARATE_RECOVERY := true
TARGET_BOARD_PLATFORM := msm8938
TARGET_CPU_ABI := arm64-v8a
#TARGET_CPU_ABI2 := armeabi
#TARGET_ARCH_VARIANT := armv7-a-neon
#TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
#ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := E2303

BOARD_KERNEL_CMDLINE := # ignored by sony's bootloader
BOARD_KERNEL_BASE := 0x
BOARD_KERNEL_PAGESIZE := 4096

# fix this up by examining /proc/mtd on a running device
# size in bytes
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
#BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00480000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2675703808
BOARD_USERDATAIMAGE_PARTITION_SIZE := 4399824896
#BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/sony/E2303/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
